# Generated by Django 6.0.4 on 2026-06-14 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Полное имя')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('favorite_category', models.CharField(blank=True, max_length=100, verbose_name='Любимая категория')),
                ('delivery_city', models.CharField(blank=True, max_length=100, verbose_name='Город доставки')),
                ('role', models.CharField(choices=[('customer', 'Покупатель'), ('manager', 'Менеджер'), ('admin', 'Администратор')], default='customer', max_length=20, verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
